name: Generate ASCII Art

# Trigger the workflow on every push to the main branch
on:
  push:

jobs:
  ascii-job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v6

    - name: Checkout Repo files
      run: ls -lart

    - name: Executing shell script
      run: |
        chmod +x ascii-script.sh
        ./ascii-script.sh
